//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CharEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CharEvent), typeof(System.Object));
		L.RegFunction("New", _CreateCharEvent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("MOVE_END", get_MOVE_END, set_MOVE_END);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCharEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				CharEvent obj = new CharEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: CharEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MOVE_END(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, CharEvent.MOVE_END);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MOVE_END(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			CharEvent.MOVE_END = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

