//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameEnum_ActionLabelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameEnum.ActionLabel), typeof(System.Object));
		L.RegFunction("New", _CreateGameEnum_ActionLabel);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Null", get_Null, null);
		L.RegVar("Stand", get_Stand, null);
		L.RegVar("StandUp", get_StandUp, null);
		L.RegVar("Reborn", get_Reborn, null);
		L.RegVar("Run", get_Run, null);
		L.RegVar("Dash", get_Dash, null);
		L.RegVar("BackOff", get_BackOff, null);
		L.RegVar("CmdAction", get_CmdAction, null);
		L.RegVar("Dead", get_Dead, null);
		L.RegVar("Action", get_Action, null);
		L.RegVar("Idle_Wait_A", get_Idle_Wait_A, null);
		L.RegVar("Idle_Wait_B", get_Idle_Wait_B, null);
		L.RegVar("run_fwd", get_run_fwd, null);
		L.RegVar("Mvm_Jog", get_Mvm_Jog, null);
		L.RegVar("Mvm_Dash", get_Mvm_Dash, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameEnum_ActionLabel(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameEnum.ActionLabel obj = new GameEnum.ActionLabel();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameEnum.ActionLabel.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Null(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Null);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Stand(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Stand);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StandUp(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.StandUp);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Reborn(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Reborn);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Run(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Run);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Dash(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Dash);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackOff(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.BackOff);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CmdAction(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.CmdAction);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Dead(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Dead);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Action(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Action);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Idle_Wait_A(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Idle_Wait_A);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Idle_Wait_B(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Idle_Wait_B);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_run_fwd(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.run_fwd);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Mvm_Jog(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Mvm_Jog);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Mvm_Dash(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameEnum.ActionLabel.Mvm_Dash);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

