//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameEnum_Weapon_MeleeTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(GameEnum.Weapon_MeleeType));
		L.RegVar("Boxing_Glove", get_Boxing_Glove, null);
		L.RegVar("Knife", get_Knife, null);
		L.RegVar("Sword", get_Sword, null);
		L.RegVar("BroadSword", get_BroadSword, null);
		L.RegVar("DualBlades", get_DualBlades, null);
		L.RegVar("Sickle", get_Sickle, null);
		L.RegVar("Lance", get_Lance, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<GameEnum.Weapon_MeleeType>.Check = CheckType;
		StackTraits<GameEnum.Weapon_MeleeType>.Push = Push;
	}

	static void Push(IntPtr L, GameEnum.Weapon_MeleeType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(GameEnum.Weapon_MeleeType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Boxing_Glove(IntPtr L)
	{
		ToLua.Push(L, GameEnum.Weapon_MeleeType.Boxing_Glove);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Knife(IntPtr L)
	{
		ToLua.Push(L, GameEnum.Weapon_MeleeType.Knife);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sword(IntPtr L)
	{
		ToLua.Push(L, GameEnum.Weapon_MeleeType.Sword);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BroadSword(IntPtr L)
	{
		ToLua.Push(L, GameEnum.Weapon_MeleeType.BroadSword);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DualBlades(IntPtr L)
	{
		ToLua.Push(L, GameEnum.Weapon_MeleeType.DualBlades);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sickle(IntPtr L)
	{
		ToLua.Push(L, GameEnum.Weapon_MeleeType.Sickle);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Lance(IntPtr L)
	{
		ToLua.Push(L, GameEnum.Weapon_MeleeType.Lance);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		GameEnum.Weapon_MeleeType o = (GameEnum.Weapon_MeleeType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

