//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameEnum_CharStateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameEnum.CharState), typeof(System.Object));
		L.RegFunction("New", _CreateGameEnum_CharState);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Char_Idle", get_Char_Idle, set_Char_Idle);
		L.RegVar("Char_Squat", get_Char_Squat, set_Char_Squat);
		L.RegVar("Char_Prone", get_Char_Prone, set_Char_Prone);
		L.RegVar("Char_Weak", get_Char_Weak, set_Char_Weak);
		L.RegVar("Char_Dead", get_Char_Dead, set_Char_Dead);
		L.RegVar("Char_Skill", get_Char_Skill, set_Char_Skill);
		L.RegVar("Char_Swimming", get_Char_Swimming, set_Char_Swimming);
		L.RegVar("Char_Hurt", get_Char_Hurt, set_Char_Hurt);
		L.RegVar("Char_HurtLie", get_Char_HurtLie, set_Char_HurtLie);
		L.RegVar("Char_HurtLinkBone", get_Char_HurtLinkBone, set_Char_HurtLinkBone);
		L.RegVar("Char_Polymorph", get_Char_Polymorph, set_Char_Polymorph);
		L.RegVar("Char_Freeze", get_Char_Freeze, set_Char_Freeze);
		L.RegVar("Char_Swoon", get_Char_Swoon, set_Char_Swoon);
		L.RegVar("Char_Strobe", get_Char_Strobe, set_Char_Strobe);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameEnum_CharState(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameEnum.CharState obj = new GameEnum.CharState();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameEnum.CharState.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Idle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Idle);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Squat(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Squat);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Prone(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Prone);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Weak(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Weak);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Dead(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Dead);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Skill(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Skill);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Swimming(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Swimming);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Hurt(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Hurt);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_HurtLie(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_HurtLie);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_HurtLinkBone(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_HurtLinkBone);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Polymorph(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Polymorph);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Freeze(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Freeze);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Swoon(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Swoon);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Char_Strobe(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, GameEnum.CharState.Char_Strobe);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Idle(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Idle = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Squat(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Squat = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Prone(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Prone = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Weak(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Weak = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Dead(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Dead = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Skill(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Skill = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Swimming(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Swimming = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Hurt(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Hurt = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_HurtLie(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_HurtLie = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_HurtLinkBone(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_HurtLinkBone = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Polymorph(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Polymorph = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Freeze(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Freeze = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Swoon(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Swoon = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Char_Strobe(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			GameEnum.CharState.Char_Strobe = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

