//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameEnum_ItemTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(GameEnum.ItemType));
		L.RegVar("Gun", get_Gun, null);
		L.RegVar("PistolGun", get_PistolGun, null);
		L.RegVar("Melee", get_Melee, null);
		L.RegVar("Grenade", get_Grenade, null);
		L.RegVar("Slot", get_Slot, null);
		L.RegVar("Armor", get_Armor, null);
		L.RegVar("Bag", get_Bag, null);
		L.RegVar("Helmet", get_Helmet, null);
		L.RegVar("Shrup", get_Shrup, null);
		L.RegVar("Bullet", get_Bullet, null);
		L.RegVar("Drug_Boost", get_Drug_Boost, null);
		L.RegVar("Drug_Healing", get_Drug_Healing, null);
		L.RegVar("Avatar_Fashion", get_Avatar_Fashion, null);
		L.RegVar("Avatar_Suit", get_Avatar_Suit, null);
		L.RegVar("Cards", get_Cards, null);
		L.RegVar("Card_Fragment", get_Card_Fragment, null);
		L.RegVar("Card_General_Fragment", get_Card_General_Fragment, null);
		L.RegVar("Currency", get_Currency, null);
		L.RegVar("SpecialCurrency", get_SpecialCurrency, null);
		L.RegVar("ExperienceCard", get_ExperienceCard, null);
		L.RegVar("UpgradeCard", get_UpgradeCard, null);
		L.RegVar("PassCheck", get_PassCheck, null);
		L.RegVar("Reward", get_Reward, null);
		L.RegVar("RenamingCard", get_RenamingCard, null);
		L.RegVar("Decorate", get_Decorate, null);
		L.RegVar("Expression_Action", get_Expression_Action, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<GameEnum.ItemType>.Check = CheckType;
		StackTraits<GameEnum.ItemType>.Push = Push;
	}

	static void Push(IntPtr L, GameEnum.ItemType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(GameEnum.ItemType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Gun(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Gun);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PistolGun(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.PistolGun);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Melee(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Melee);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Grenade(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Grenade);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Slot(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Slot);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Armor(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Armor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Bag(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Bag);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Helmet(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Helmet);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Shrup(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Shrup);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Bullet(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Bullet);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Drug_Boost(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Drug_Boost);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Drug_Healing(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Drug_Healing);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Avatar_Fashion(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Avatar_Fashion);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Avatar_Suit(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Avatar_Suit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cards(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Cards);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Card_Fragment(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Card_Fragment);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Card_General_Fragment(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Card_General_Fragment);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Currency(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Currency);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SpecialCurrency(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.SpecialCurrency);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExperienceCard(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.ExperienceCard);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UpgradeCard(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.UpgradeCard);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PassCheck(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.PassCheck);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Reward(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Reward);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RenamingCard(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.RenamingCard);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Decorate(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Decorate);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Expression_Action(IntPtr L)
	{
		ToLua.Push(L, GameEnum.ItemType.Expression_Action);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		GameEnum.ItemType o = (GameEnum.ItemType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

