//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ItemWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Item), typeof(ActionObj));
		L.RegFunction("getOwner", getOwner);
		L.RegFunction("initData", initData);
		L.RegFunction("onViewLoadFin", onViewLoadFin);
		L.RegFunction("OnPickUp", OnPickUp);
		L.RegFunction("DropItem", DropItem);
		L.RegFunction("OnGround", OnGround);
		L.RegFunction("IsGrounded", IsGrounded);
		L.RegFunction("getItemType", getItemType);
		L.RegFunction("onGet", onGet);
		L.RegFunction("onRecycle", onRecycle);
		L.RegFunction("onRelease", onRelease);
		L.RegFunction("New", _CreateItem);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("itemData", get_itemData, set_itemData);
		L.RegVar("isWeapon", get_isWeapon, set_isWeapon);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateItem(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Item obj = new Item();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Item.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getOwner(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			Player o = obj.getOwner();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int initData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			obj.initData();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onViewLoadFin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			obj.onViewLoadFin();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPickUp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			Player arg0 = (Player)ToLua.CheckObject<Player>(L, 2);
			obj.OnPickUp(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DropItem(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			obj.DropItem();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGround(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			obj.OnGround();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsGrounded(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			bool o = obj.IsGrounded();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getItemType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			GameEnum.ItemType o = obj.getItemType();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onGet(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			obj.onGet();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onRecycle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			obj.onRecycle();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onRelease(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Item obj = (Item)ToLua.CheckObject<Item>(L, 1);
			obj.onRelease();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_itemData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Item obj = (Item)o;
			ItemData ret = obj.itemData;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index itemData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isWeapon(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Item obj = (Item)o;
			bool ret = obj.isWeapon;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isWeapon on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_itemData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Item obj = (Item)o;
			ItemData arg0 = (ItemData)ToLua.CheckObject<ItemData>(L, 2);
			obj.itemData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index itemData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isWeapon(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Item obj = (Item)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isWeapon = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isWeapon on a nil value");
		}
	}
}

