//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MovePartWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MovePart), typeof(System.Object));
		L.RegFunction("PauseMove", PauseMove);
		L.RegFunction("PesumeMove", PesumeMove);
		L.RegFunction("Init", Init);
		L.RegFunction("Update", Update);
		L.RegFunction("InitSpeed", InitSpeed);
		L.RegFunction("StartMove", StartMove);
		L.RegFunction("StartMoveToByList", StartMoveToByList);
		L.RegFunction("StartMoveTo", StartMoveTo);
		L.RegFunction("StopMove", StopMove);
		L.RegFunction("IsMove", IsMove);
		L.RegFunction("IsAir", IsAir);
		L.RegFunction("IsJumping", IsJumping);
		L.RegFunction("IsFollowTarget", IsFollowTarget);
		L.RegFunction("GetNextMoveSpeedDic", GetNextMoveSpeedDic);
		L.RegFunction("SetTargetRotation", SetTargetRotation);
		L.RegFunction("SetTargetDir", SetTargetDir);
		L.RegFunction("getTargetDir", getTargetDir);
		L.RegFunction("followMyTarget", followMyTarget);
		L.RegFunction("chkFollowTarget", chkFollowTarget);
		L.RegFunction("startFollowTarget", startFollowTarget);
		L.RegFunction("SetFollowTarget", SetFollowTarget);
		L.RegFunction("cancelFollowTarget", cancelFollowTarget);
		L.RegFunction("SetRotation", SetRotation);
		L.RegFunction("getRotation", getRotation);
		L.RegFunction("changeDir", changeDir);
		L.RegFunction("Jump", Jump);
		L.RegFunction("calJumpSpeed", calJumpSpeed);
		L.RegFunction("startMoveToByListWithReverseList", startMoveToByListWithReverseList);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("reset", reset);
		L.RegFunction("New", _CreateMovePart);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("forwardDirection", get_forwardDirection, set_forwardDirection);
		L.RegVar("faceToRotation", get_faceToRotation, set_faceToRotation);
		L.RegVar("rotateSpeed", get_rotateSpeed, set_rotateSpeed);
		L.RegVar("isRotateLessSpeed", get_isRotateLessSpeed, set_isRotateLessSpeed);
		L.RegVar("movePoint", get_movePoint, set_movePoint);
		L.RegVar("useGravityPower", get_useGravityPower, set_useGravityPower);
		L.RegVar("GravityPower", get_GravityPower, set_GravityPower);
		L.RegVar("targetPos", get_targetPos, set_targetPos);
		L.RegVar("hasTarget", get_hasTarget, set_hasTarget);
		L.RegVar("speed", get_speed, set_speed);
		L.RegVar("jumpState", get_jumpState, set_jumpState);
		L.RegVar("upPow", get_upPow, set_upPow);
		L.RegVar("acceleratedupPow", get_acceleratedupPow, set_acceleratedupPow);
		L.RegVar("ZeroUpStop", get_ZeroUpStop, set_ZeroUpStop);
		L.RegVar("useYspeed", get_useYspeed, set_useYspeed);
		L.RegVar("AcceleratedSpeed", get_AcceleratedSpeed, set_AcceleratedSpeed);
		L.RegVar("MaxSpeed", get_MaxSpeed, set_MaxSpeed);
		L.RegVar("ZeroSpeedStop", get_ZeroSpeedStop, set_ZeroSpeedStop);
		L.RegVar("useMovePoint", get_useMovePoint, set_useMovePoint);
		L.RegVar("useWeightPower", get_useWeightPower, set_useWeightPower);
		L.RegVar("ImmDir", get_ImmDir, set_ImmDir);
		L.RegVar("target", get_target, set_target);
		L.RegVar("targetOffset", get_targetOffset, set_targetOffset);
		L.RegVar("extraAcSpeed", get_extraAcSpeed, set_extraAcSpeed);
		L.RegVar("extraCurSpeed", get_extraCurSpeed, set_extraCurSpeed);
		L.RegVar("extraSpeed", get_extraSpeed, set_extraSpeed);
		L.RegVar("extraDir", get_extraDir, set_extraDir);
		L.RegVar("extraMaxSpeed", get_extraMaxSpeed, set_extraMaxSpeed);
		L.RegVar("extraMoveStartTime", get_extraMoveStartTime, set_extraMoveStartTime);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMovePart(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				ObjBase arg0 = (ObjBase)ToLua.CheckObject<ObjBase>(L, 1);
				MovePart obj = new MovePart(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MovePart.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PauseMove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.PauseMove();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PesumeMove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.PesumeMove();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.Update();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitSpeed(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.InitSpeed();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartMove(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				obj.StartMove(arg0);
				return 0;
			}
			else if (count == 3)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.StartMove(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MovePart.StartMove");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartMoveToByList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			System.Collections.Generic.List<UnityEngine.Vector3> arg0 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
			obj.StartMoveToByList(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartMoveTo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				obj.StartMoveTo(arg0);
				return 0;
			}
			else if (count == 3)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.StartMoveTo(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MovePart.StartMoveTo");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopMove(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				obj.StopMove();
				return 0;
			}
			else if (count == 2)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				obj.StopMove(arg0);
				return 0;
			}
			else if (count == 3)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.StopMove(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				obj.StopMove(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MovePart.StopMove");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsMove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			bool o = obj.IsMove();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsAir(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			bool o = obj.IsAir();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsJumping(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			bool o = obj.IsJumping();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsFollowTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			bool o = obj.IsFollowTarget();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNextMoveSpeedDic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			UnityEngine.Vector3 o = obj.GetNextMoveSpeedDic();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTargetRotation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetTargetRotation(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTargetDir(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.SetTargetDir(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getTargetDir(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			UnityEngine.Vector3 o = obj.getTargetDir();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int followMyTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.followMyTarget();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int chkFollowTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			bool o = obj.chkFollowTarget();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int startFollowTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			ObjBase arg0 = (ObjBase)ToLua.CheckObject<ObjBase>(L, 2);
			obj.startFollowTarget(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFollowTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			ObjBase arg0 = (ObjBase)ToLua.CheckObject<ObjBase>(L, 2);
			obj.SetFollowTarget(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int cancelFollowTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.cancelFollowTarget();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetRotation(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				obj.SetRotation(arg0);
				return 0;
			}
			else if (count == 3)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.SetRotation(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MovePart.SetRotation");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getRotation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Vector3 o = obj.getRotation(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int changeDir(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.changeDir(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Jump(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.Jump();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int calJumpSpeed(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.calJumpSpeed();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int startMoveToByListWithReverseList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			System.Collections.Generic.List<UnityEngine.Vector3> arg0 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
			obj.startMoveToByListWithReverseList(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int reset(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				obj.reset();
				return 0;
			}
			else if (count == 2)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				obj.reset(arg0);
				return 0;
			}
			else if (count == 3)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.reset(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				MovePart obj = (MovePart)ToLua.CheckObject<MovePart>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				obj.reset(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MovePart.reset");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_forwardDirection(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			UnityEngine.Vector3 ret = obj.forwardDirection;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index forwardDirection on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_faceToRotation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.faceToRotation;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index faceToRotation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_rotateSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.rotateSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rotateSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isRotateLessSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.isRotateLessSpeed;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isRotateLessSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_movePoint(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.movePoint;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index movePoint on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_useGravityPower(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.useGravityPower;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useGravityPower on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GravityPower(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.GravityPower;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GravityPower on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_targetPos(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			UnityEngine.Vector3 ret = obj.targetPos;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetPos on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hasTarget(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.hasTarget;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hasTarget on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_speed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.speed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index speed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_jumpState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			GameEnum.JumpState ret = obj.jumpState;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index jumpState on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_upPow(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.upPow;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index upPow on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_acceleratedupPow(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.acceleratedupPow;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index acceleratedupPow on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ZeroUpStop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.ZeroUpStop;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ZeroUpStop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_useYspeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.useYspeed;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useYspeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AcceleratedSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.AcceleratedSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AcceleratedSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MaxSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.MaxSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MaxSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ZeroSpeedStop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.ZeroSpeedStop;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ZeroSpeedStop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_useMovePoint(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.useMovePoint;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useMovePoint on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_useWeightPower(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.useWeightPower;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useWeightPower on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ImmDir(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool ret = obj.ImmDir;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ImmDir on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_target(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			ObjBase ret = obj.target;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index target on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_targetOffset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			UnityEngine.Vector3 ret = obj.targetOffset;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetOffset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_extraAcSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.extraAcSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraAcSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_extraCurSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.extraCurSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraCurSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_extraSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.extraSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_extraDir(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.extraDir;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraDir on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_extraMaxSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.extraMaxSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraMaxSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_extraMoveStartTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float ret = obj.extraMoveStartTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraMoveStartTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_forwardDirection(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.forwardDirection = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index forwardDirection on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_faceToRotation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.faceToRotation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index faceToRotation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_rotateSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.rotateSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rotateSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isRotateLessSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isRotateLessSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isRotateLessSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_movePoint(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.movePoint = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index movePoint on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_useGravityPower(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.useGravityPower = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useGravityPower on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GravityPower(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.GravityPower = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GravityPower on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_targetPos(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.targetPos = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetPos on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_hasTarget(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.hasTarget = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hasTarget on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_speed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.speed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index speed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_jumpState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			GameEnum.JumpState arg0 = (GameEnum.JumpState)ToLua.CheckObject(L, 2, typeof(GameEnum.JumpState));
			obj.jumpState = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index jumpState on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_upPow(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.upPow = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index upPow on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_acceleratedupPow(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.acceleratedupPow = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index acceleratedupPow on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ZeroUpStop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.ZeroUpStop = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ZeroUpStop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_useYspeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.useYspeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useYspeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AcceleratedSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.AcceleratedSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AcceleratedSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MaxSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.MaxSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MaxSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ZeroSpeedStop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.ZeroSpeedStop = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ZeroSpeedStop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_useMovePoint(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.useMovePoint = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useMovePoint on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_useWeightPower(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.useWeightPower = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useWeightPower on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ImmDir(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.ImmDir = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ImmDir on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_target(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			ObjBase arg0 = (ObjBase)ToLua.CheckObject<ObjBase>(L, 2);
			obj.target = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index target on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_targetOffset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.targetOffset = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetOffset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_extraAcSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.extraAcSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraAcSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_extraCurSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.extraCurSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraCurSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_extraSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.extraSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_extraDir(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.extraDir = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraDir on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_extraMaxSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.extraMaxSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraMaxSpeed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_extraMoveStartTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MovePart obj = (MovePart)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.extraMoveStartTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index extraMoveStartTime on a nil value");
		}
	}
}

