//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PlayerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Player), typeof(Character));
		L.RegFunction("init", init);
		L.RegFunction("initData", initData);
		L.RegFunction("initAvatar", initAvatar);
		L.RegFunction("ChangeNodeObj", ChangeNodeObj);
		L.RegFunction("ChangePart", ChangePart);
		L.RegFunction("OnItemTrigger", OnItemTrigger);
		L.RegFunction("EquipWeapon", EquipWeapon);
		L.RegFunction("EquipNearWeapon", EquipNearWeapon);
		L.RegFunction("PickUpNearItem", PickUpNearItem);
		L.RegFunction("OnEvent", OnEvent);
		L.RegFunction("onGet", onGet);
		L.RegFunction("onRecycle", onRecycle);
		L.RegFunction("onRelease", onRelease);
		L.RegFunction("New", _CreatePlayer);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("avatar", get_avatar, set_avatar);
		L.RegVar("weaponSystem", get_weaponSystem, set_weaponSystem);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePlayer(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Player obj = new Player();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Player.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			obj.init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int initData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			obj.initData();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int initAvatar(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string[] arg1 = ToLua.CheckStringArray(L, 3);
			obj.initAvatar(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeNodeObj(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
				obj.ChangeNodeObj(arg0);
				return 0;
			}
			else if (count == 3)
			{
				Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.ChangeNodeObj(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Player.ChangeNodeObj");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangePart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ChangePart(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnItemTrigger(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
				Item arg0 = (Item)ToLua.CheckObject<Item>(L, 2);
				obj.OnItemTrigger(arg0);
				return 0;
			}
			else if (count == 3)
			{
				Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
				Item arg0 = (Item)ToLua.CheckObject<Item>(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.OnItemTrigger(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Player.OnItemTrigger");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EquipWeapon(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			Item arg0 = (Item)ToLua.CheckObject<Item>(L, 2);
			obj.EquipWeapon(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EquipNearWeapon(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			obj.EquipNearWeapon();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PickUpNearItem(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			obj.PickUpNearItem();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				obj.OnEvent(arg0);
				return 0;
			}
			else if (count == 3)
			{
				Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				object[] arg1 = ToLua.CheckObjectArray(L, 3);
				obj.OnEvent(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Player.OnEvent");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onGet(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			obj.onGet();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onRecycle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			obj.onRecycle();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onRelease(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Player obj = (Player)ToLua.CheckObject<Player>(L, 1);
			obj.onRelease();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_avatar(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Player obj = (Player)o;
			AvatarSystem ret = obj.avatar;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index avatar on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_weaponSystem(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Player obj = (Player)o;
			WeaponSystem ret = obj.weaponSystem;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index weaponSystem on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_avatar(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Player obj = (Player)o;
			AvatarSystem arg0 = (AvatarSystem)ToLua.CheckObject<AvatarSystem>(L, 2);
			obj.avatar = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index avatar on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_weaponSystem(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Player obj = (Player)o;
			WeaponSystem arg0 = (WeaponSystem)ToLua.CheckObject<WeaponSystem>(L, 2);
			obj.weaponSystem = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index weaponSystem on a nil value");
		}
	}
}

