//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SystemEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SystemEvent), typeof(System.Object));
		L.RegFunction("New", _CreateSystemEvent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("LUA_INIT_COMPLETE", get_LUA_INIT_COMPLETE, set_LUA_INIT_COMPLETE);
		L.RegVar("UI_HUD_ON_ROTATE_TOUCH_MOVE", get_UI_HUD_ON_ROTATE_TOUCH_MOVE, set_UI_HUD_ON_ROTATE_TOUCH_MOVE);
		L.RegVar("UI_HUD_ON_ROTATE_TOUCH_STATE", get_UI_HUD_ON_ROTATE_TOUCH_STATE, set_UI_HUD_ON_ROTATE_TOUCH_STATE);
		L.RegVar("UI_HUD_ON_JOYSTICK_MOVE", get_UI_HUD_ON_JOYSTICK_MOVE, set_UI_HUD_ON_JOYSTICK_MOVE);
		L.RegVar("UI_HUD_ON_JOYSTICK_UP", get_UI_HUD_ON_JOYSTICK_UP, set_UI_HUD_ON_JOYSTICK_UP);
		L.RegVar("UI_BAT_ON_SPRINT_STATE", get_UI_BAT_ON_SPRINT_STATE, set_UI_BAT_ON_SPRINT_STATE);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSystemEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SystemEvent obj = new SystemEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SystemEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LUA_INIT_COMPLETE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, SystemEvent.LUA_INIT_COMPLETE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UI_HUD_ON_ROTATE_TOUCH_MOVE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, SystemEvent.UI_HUD_ON_ROTATE_TOUCH_MOVE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UI_HUD_ON_ROTATE_TOUCH_STATE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, SystemEvent.UI_HUD_ON_ROTATE_TOUCH_STATE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UI_HUD_ON_JOYSTICK_MOVE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, SystemEvent.UI_HUD_ON_JOYSTICK_MOVE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UI_HUD_ON_JOYSTICK_UP(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, SystemEvent.UI_HUD_ON_JOYSTICK_UP);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UI_BAT_ON_SPRINT_STATE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, SystemEvent.UI_BAT_ON_SPRINT_STATE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LUA_INIT_COMPLETE(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			SystemEvent.LUA_INIT_COMPLETE = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UI_HUD_ON_ROTATE_TOUCH_MOVE(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			SystemEvent.UI_HUD_ON_ROTATE_TOUCH_MOVE = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UI_HUD_ON_ROTATE_TOUCH_STATE(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			SystemEvent.UI_HUD_ON_ROTATE_TOUCH_STATE = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UI_HUD_ON_JOYSTICK_MOVE(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			SystemEvent.UI_HUD_ON_JOYSTICK_MOVE = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UI_HUD_ON_JOYSTICK_UP(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			SystemEvent.UI_HUD_ON_JOYSTICK_UP = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UI_BAT_ON_SPRINT_STATE(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			SystemEvent.UI_BAT_ON_SPRINT_STATE = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

